version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
