version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodb_data:
